//
//  PlayerManager.swift
//  MyApp
//

import Foundation
import AVFoundation
import SwiftUI
import EPUBKit
import SwiftEdgeTTS

@Observable
class PlayerManager: NSObject, AVAudioPlayerDelegate {
    var activeBook: VoxBook?
    var currentParagraphs: [String] = []
    var currentParaIdx: Int = 0
    var isPlaying: Bool = false
    var isFullReaderPresented: Bool = false
    var selectedVoice: String = "en-US-BrianNeural"
    
    @ObservationIgnored private var audioPlayer: AVAudioPlayer?
    @ObservationIgnored private var currentEPUBDocument: EPUBDocument?
    
    // Create the TTS Service instance specific to the herrkaefer package
    @ObservationIgnored private let ttsService = EdgeTTSService()
    
    override init() {
        super.init()
        setupAudioSession()
    }
    
    private func setupAudioSession() {
        Task {
            do {
                try AVAudioSession.sharedInstance().setCategory(.playback, mode: .spokenAudio)
                try AVAudioSession.sharedInstance().setActive(true)
            } catch {
                print("Failed to set audio session category: \(error)")
            }
        }
    } // <--- THIS BRACKET WAS MISSING
        
    func loadChapter(index: Int) {
        guard let book = activeBook else { return }
        self.currentParaIdx = 0
        self.isPlaying = false
        self.audioPlayer?.stop()
        
        // If we haven't loaded the EPUB kit document for this session, load it now
        if currentEPUBDocument?.title != book.title {
            let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(book.id).epub")
            try? book.epubData.write(to: tempURL)
            currentEPUBDocument = EPUBDocument(url: tempURL)
        }
        
        // 1. Guard only the Optionals and conditions that might fail
        guard let document = currentEPUBDocument,
              index < book.chapterFiles.count else { return }
        
        // 2. Assign contentDirectory normally (it is a guaranteed non-optional URL)
        let contentDir = document.contentDirectory
        
        let chapterPath = book.chapterFiles[index]
        
        // FIX: `.appendingPathComponent` returns a non-optional URL, so we just use `let`.
        let chapterURL = contentDir.appendingPathComponent(chapterPath)
        
        // FIX: Added `encoding: .utf8` to remove the iOS 18 deprecation warning.
        if let htmlString = try? String(contentsOf: chapterURL, encoding: .utf8) {
            self.currentParagraphs = extractTextParagraphs(fromHTML: htmlString)
        }
    }
    
    func playParagraph(at index: Int) {
        guard index >= 0 && index < currentParagraphs.count else {
            isPlaying = false
            return
        }
        
        self.currentParaIdx = index
        self.isPlaying = true
        self.audioPlayer?.stop()
        
        let textToRead = currentParagraphs[index]
        
        Task {
            do {
                // The herrkaefer package needs to save the file locally first.
                // We create a unique temporary file path for this specific paragraph.
                let tempFileName = "paragraph_\(index).mp3"
                let outputURL = FileManager.default.temporaryDirectory.appendingPathComponent(tempFileName)
                
                // Remove the old file if it already exists to prevent playback issues
                if FileManager.default.fileExists(atPath: outputURL.path) {
                    try? FileManager.default.removeItem(at: outputURL)
                }
                
                // 3. UPDATE THIS: Use the selected voice instead of hardcoding
                let audioURL = try await ttsService.synthesize(
                    text: textToRead,
                    voice: self.selectedVoice,
                    outputURL: outputURL
                )
                DispatchQueue.main.async { [weak self = self] in
                    guard let self = self else { return }
                    do {
                        // Play the audio file generated by the TTS service
                        self.audioPlayer = try AVAudioPlayer(contentsOf: audioURL)
                        self.audioPlayer?.delegate = self
                        self.audioPlayer?.play()
                    } catch {
                        print("Audio Playback Error: \(error)")
                        self.isPlaying = false
                    }
                }
            } catch {
                print("SwiftEdgeTTS Error: \(error)")
                DispatchQueue.main.async { self.isPlaying = false }
            }
        }
    }
    
    func togglePlayPause() {
        if isPlaying {
            audioPlayer?.pause()
            isPlaying = false
        } else {
            if let player = audioPlayer, !player.isPlaying {
                player.play()
                isPlaying = true
            } else {
                playParagraph(at: currentParaIdx)
            }
        }
    }
    
    func nextChapter() {
        guard let book = activeBook, book.currentChapterIdx + 1 < book.chapters.count else { return }
        book.currentChapterIdx += 1
        loadChapter(index: book.currentChapterIdx)
    }
    
    func prevChapter() {
        guard let book = activeBook, book.currentChapterIdx - 1 >= 0 else { return }
        book.currentChapterIdx -= 1
        loadChapter(index: book.currentChapterIdx)
    }
    
    // MARK: - AVAudioPlayerDelegate
    
    func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        if flag && isPlaying {
            playParagraph(at: currentParaIdx + 1)
        }
    }
    
    // MARK: - HTML Parsing Helper
    private func extractTextParagraphs(fromHTML html: String) -> [String] {
        let regex = try! NSRegularExpression(pattern: "<p[^>]*>(.*?)</p>", options: [.caseInsensitive, .dotMatchesLineSeparators])
        let matches = regex.matches(in: html, range: NSRange(html.startIndex..., in: html))
        
        var paragraphs: [String] = []
        for match in matches {
            if let range = Range(match.range(at: 1), in: html) {
                let rawText = String(html[range])
                let cleanText = rawText.replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression, range: nil)
                    .replacingOccurrences(of: "&nbsp;", with: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                
                if !cleanText.isEmpty {
                    paragraphs.append(cleanText)
                }
            }
        }
        
        if paragraphs.isEmpty {
            let cleanText = html.replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression, range: nil)
            paragraphs = cleanText.components(separatedBy: .newlines).filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
        }
        
        return paragraphs
    }
}
